[[redirects]]
  from = "https://surinametimemachine.org/*"
  to = "https://surinametijdmachine.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.surinametimemachine.org/*"
  to = "https://surinametijdmachine.org/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*" # see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
